Внесение изменений

diff --git a/.github/workflows/deploy-app.yml b/.github/workflows/deploy-app.yml
--- a/.github/workflows/deploy-app.yml
+++ b/.github/workflows/deploy-app.yml
@@ -62,15 +62,15 @@ jobs:
           exit 1
         fi
         # Проверка существования deployment
-        if ! kubectl get deployment aleksandrov-my-mini-app --kubeconfig ~/.kube/config > /dev/null 2>&1; then
-          echo "ERROR: Deployment 'aleksandrov-my-mini-app' not found"
+        if ! kubectl get deployment my-mini-app --kubeconfig ~/.kube/config > /dev/null 2>&1; then
+          echo "ERROR: Deployment 'my-mini-app' not found"
           exit 1
         fi
 
         # Обновление deployment
-        kubectl set image deployment/aleksandrov-my-mini-app \
+        kubectl set image deployment/my-mini-app \
           my-mini-app=${{ secrets.DOCKER_HUB_USERNAME }}/aleksandrov-my-miniapp:${{ steps.docker-tag.outputs.tag }} --kubeconfig ~/.kube/config
 
     - name: Verify deployment
       if: startsWith(github.ref, 'refs/tags/')
-      run: kubectl rollout status deployment/aleksandrov-my-miniapp --kubeconfig ~/.kube/config
+      run: kubectl rollout status deployment/my-mini-app --kubeconfig ~/.kube/config
